### ISSUE TITLE
Add downstream testing

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaArrays/ArrayInterface.jl#193]
It seems that there is a lot of churn here and this is a Base library, so we should add downstream testing and require that any PR here has associated downstream PRs that fix any breakage. I think downstream tests on OrdinaryDiffEq and LoopVectorization are at least in order. @chriselrod

**Comment by Tokazama** [comment]
Has there been any progress on this front? I've been looking at moving the BlockArray stuff out and I'm curious if it would be sufficient to just have those libraries support `findstructralnz` using their own methods instead of defining `BandedBlockBandedMatrixIndex`, `BandedMatrixIndex`, and `BlockBandedMatrixIndex`.
